[package]
edition = { workspace = true }
name = "workers"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-sesv2 = { workspace = true }
aws-sdk-sns = { workspace = true }
aws-types = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
ctrlc = { workspace = true }
futures = { workspace = true }
isocountry = { workspace = true }
itertools = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }

# path dependencies
account = { workspace = true }
bdk_utils = { workspace = true }
chain_indexer = { workspace = true }
database = { workspace = true }
errors = { workspace = true }
feature_flags = { workspace = true }
metrics = { workspace = true }
notification = { workspace = true }
notification_validation = { workspace = true }
queue = { workspace = true }
recovery = { workspace = true }
types = { workspace = true, features = ["account", "notification"] }
