port_name: mfgtest_port

messages:
  protos:
    - name: fwpb_mfgtest_fingerprint_cmd
      auth: never
    - name: fwpb_mfgtest_serial_write_cmd
      auth: never
    - name: fwpb_mfgtest_gpio_cmd
      auth: never
    - name: fwpb_mfgtest_battery_variant_cmd
      auth: never
