services:
  bitcoind:
    build: bitcoind
    command: -signet
    ports:
      - 38333

  fulcrum:
    build: fulcrum
    command: --rpccookie=/var/lib/bitcoin/signet/.cookie --bitcoind=bitcoind:38332
    ports:
      - 51002
    volumes_from:
      - bitcoind:ro

  esplora:
    build: esplora-electrs
    command:
      --daemon-rpc-addr=bitcoind:38332
      --daemon-dir=/var/lib/bitcoin/
    ports:
      - 9000:9000
    volumes_from:
      - bitcoind:ro

